market/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^accounts/', include('registration.backends.default.urls')),
    url(r'^admin/', admin.site.urls),
    url(r'^products/', include('products.urls', namespace='products')),
]

products/urls.py
from django.conf.urls import url

from products import views

urlpatterns = [
    url(r'^$', views.ProductListView.as_view(), name='list-products'),
    url(r'^add/$', views.ProductCreateView.as_view(), name='create-products'),
    url(r'^update/(?P<pk>\d+)/$', views.ProductUpdateView.as_view(), name='update-products'),
    url(r'^detail/(?P<pk>\d+)/$', views.ProductDetailView.as_view(), name='detail-products'),
    url(r'^delete/(?P<pk>\d+)/$', views.ProductDeleteView.as_view(), name='delete-products'),
    url(r'^units/$', views.UnitListView.as_view(), name='list-units'),
    url(r'^units/add/$', views.UnitCreateView.as_view(), name='create-units'),
    url(r'^units/update/(?P<pk>\d+)/$', views.UnitUpdateView.as_view(), name='update-units'),
    url(r'^units/delete/(?P<pk>\d+)/$', views.UnitDeleteView.as_view(), name='delete-units'),
]

products/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models
from django.urls import reverse

# Create your models here.

class Unit(models.Model):
    name = models.CharField(max_length=30, unique=True)
    symbol = models.CharField(max_length=5)
    description = models.TextField()

    def __unicode__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('products.views.unit', args=[str(self.pk)])

class Product(models.Model):
    name = models.CharField(max_length=30)
    brand = models.CharField(max_length=30, null=True, blank=True)
    serial_number = models.CharField(max_length=30, null=True, blank=True)
    manufacturer = models.CharField(max_length=30, null=True, blank=True)
    description = models.TextField()
    short_description = models.CharField(max_length=255, blank=True)
    components = models.ManyToManyField('self', null=True, blank=True)

    def __unicode__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('products.views.ProductDetailView', args=[str(self.pk)])

class Feature(models.Model):
    name = models.CharField(max_length=30)
    quantity = models.FloatField()
    units = models.OneToOneField(Unit, related_name='unit_of')
    description = models.TextField()
    product = models.ForeignKey(Product, related_name='features', null=True, blank=True)

    def __unicode__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('products.views.feature', args=[str(self.pk)])

products/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

# from django.shortcuts import render
from django.views.generic import ListView, CreateView, DetailView, UpdateView, DeleteView
from django.urls import reverse_lazy
from products.models import Unit, Product

class UnitListView(ListView):
    model = Unit
    template_name = 'unit_list.html'

class UnitCreateView(CreateView):
    model = Unit
    fields = ['name','symbol','description']
    template_name = 'unit_add.html'
    success_url = reverse_lazy('products:list-units')

class UnitUpdateView(UpdateView):
    model = Unit
    fields = ['name','symbol','description']
    template_name = 'unit_update.html'
    success_url = reverse_lazy('products:list-units')

class UnitDeleteView(DeleteView):
    model = Unit
    template_name = 'unit_delete.html'
    success_url = reverse_lazy('products:list-units')

class ProductListView(ListView):
    model = Product
    template_name = 'product_list.html'

class ProductCreateView(CreateView):
    model = Product
    fields = ['name','brand','serial_number','manufacturer','description','short_description','components']
    template_name = 'product_add.html'
    success_url = reverse_lazy('products:list-products')

class ProductDetailView(DetailView):
    model = Product
    fields = ['name','brand','serial_number','manufacturer','description','short_description','components']
    template_name = 'product_detail.html'
    success_url = reverse_lazy('products:list-products')

class ProductUpdateView(UpdateView):
    model = Product
    fields = ['name','brand','serial_number','manufacturer','description','short_description','components']
    template_name = 'product_update.html'
    success_url = reverse_lazy('products:list-products')

class ProductDeleteView(DeleteView):
    model = Product
    template_name = 'product_delete.html'
    success_url = reverse_lazy('products:list-products')

products/templates/product_add.html
{% extends 'base.html' %}
{% block content%}
<h1>Create Unit</h1>
<form method="post" action="">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="save"/>
</form>
{% endblock %}

products/templates/product_delete.html
{% extends 'base.html' %}
{% block content%}
<h1>Delete Unit {{ object }}</h1>
<form method="post" action="">
    {% csrf_token %}
    Are you sure to delete this unit?
    <input type="submit" value="yes"/>
</form>
{% endblock %}

products/templates/product_detail.html
{% extends 'base.html' %}
{% block content%}
<h1>Product {{ object }}</h1>
{% endblock %}

products/templates/product_list.html
{% extends 'base.html' %}
{% block content %}
<h1>Products</h1>
    <a href ="{% url 'products:create-products' %}">Add a product</a>
    <table>
        <tr>
            <td>Product</td>
        </tr>
        {% for product in object_list %}
        <td><a href="{% url 'products:detail-products' product.pk %}">{{ product }}</a></td>
        {% endfor %}
    </table>
{% endblock %}

products/templates/product_update.html
{% extends 'base.html' %}
{% block content%}
<h1>Update Unit {{ object }}</h1>
<form method="post" action="">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="save"/>
</form>
{% endblock %}

products/templates/unit_add.html
{% extends 'base.html' %}
{% block content%}
<h1>Create Unit</h1>
<form method="post" action="">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="save"/>
</form>
{% endblock %}

products/templates/unit_delete.html
{% extends 'base.html' %}
{% block content%}
<h1>Delete Unit {{ object }}</h1>
<form method="post" action="">
    {% csrf_token %}
    Are you sure to delete this unit?
    <input type="submit" value="yes"/>
</form>
{% endblock %}

products/templates/unit_list.html
{% extends 'base.html' %}
{% block content %}
<h1>Units</h1>
    <a href ="{% url 'products:create-units' %}">Add a unit</a>
    <table>
        <tr>
            <td>Unit</td>
            <td>Symbol</td>
        </tr>
        {% for unit in object_list %}
            <td>{{ unit }}</td>
            <td>{{ unit.symbol }}</td>
            <td><a href="{% url 'products:update-units' unit.pk %}">Update</a></td>
            <td><a href="{% url 'products:delete-units' unit.pk %}">Delete</a></td>
        {% endfor %}
    </table>
{% endblock %}

products/templates/unit_update.html
{% extends 'base.html' %}
{% block content%}
<h1>Update Unit {{ object }}</h1>
<form method="post" action="">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="save"/>
</form>
{% endblock %}

templates/base.html
{% load i18n %}
<!DOCTYPE html>
<html lang="en">

<head>
    <link rel="stylesheet" href="{{ STATIC_URL }}style.css" />
    <title>{% block title %}User test{% endblock %}</title>
</head>

<body>
    <div id="header">
    {% block header %}
    <a href="/">{% trans "Home" %}</a> | 

    {% if user.is_authenticated %}
        {% trans "Logged in" %}: {{ user.username }} 
        (<a href="{% url 'auth_logout' %}">{% trans "Log out" %}</a> | 
        <a href="{% url 'auth_password_change' %}">{% trans "Change password" %}</a>)
    {% else %}
       <a href="{% url 'auth_login' %}">{% trans "Log in" %}</a>
    {% endif %}
    <hr />
    {% endblock %}
    </div>

    <div id="content">
    {% block content %}{% endblock %}
    </div>

    <div id="footer">
    {% block footer %}
        <hr />
    {% endblock %}
    </div>
</body>

</html>